language: cpp
dist: trusty
sudo: false

env:
  global:
    - BOOST_VERSION=1_65_1
  matrix:
    - CI_BUILD=cmake CI_BUILD_TYPE=Debug
#  - CI_BUILD=cmake CI_BUILD_TYPE=Release
#  - CI_BUILD=autotools

compiler: gcc

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages:
      - g++-7
      - autoconf
      - automake
      - autotools-dev
      - libtool
      - pkg-config
      - zlib1g-dev
      - libcunit1-dev
      - libssl-dev
      - libxml2-dev
      - libev-dev
      - libevent-dev
      - libjansson-dev
      - libjemalloc-dev
      - libc-ares-dev
      - cmake
      - cmake-data
        
before_install:
  - $CC --version
  - if [[ "$CXX" = "g++" ]]; then export CXX="g++-7" CC="gcc-7"; fi
  - $CC --version
  - go version
  - cmake --version
  # Download Boost
  - cd ${HOME}
  - wget -O boost.tar.bz2 https://dl.bintray.com/boostorg/release/`echo -n ${BOOST_VERSION} | sed 's/_/./g'`/source/boost_${BOOST_VERSION}.tar.bz2
  - tar --bzip2 -xf boost.tar.bz2
  - rm boost.tar.bz2
  # Build and install Boost
  - echo -n "using gcc : : g++-7 ;" > tools/build/src/user-config.jam
  - cd boost_${BOOST_VERSION}
  - ./bootstrap.sh --with-toolset=gcc
  - export B2_OPTIONS="
    --with-system
    --with-thread
    --with-date_time
    --with-regex
    --with-serialization
    --build-type=minimal
    --prefix=${HOME}/boost
    "
  - export B2_PROPERTIES="
    threading=multi
    link-static
    variant=${CI_BUILD_TYPE,,}
    toolset=gcc
    "
  - b2 ${B2_OPTIONS} ${B2_PROPERTIES} install
  - ls -l ${HOME}/boost
before_script:
  # Now build nghttp2
  - if [[ "${CI_BUILD}" = "autotools" ]]; then autoreconf -i; fi
  - git submodule update --init
  - if [[ "${CI_BUILD}" = "autotools" ]]; then ./configure --with-mruby; fi
  - if [[ "${CI_BUILD}" = "cmake" ]]; then
    cmake
    -DCMAKE_BUILD_TYPE=${CI_BUILD_TYPE}
    -DENABLE_ASIO_LIB=ON
    -DENABLE_WERROR=1
    -DWITH_MRUBY=1
    -DWITH_NEVERBLEED=1
    ; fi
script:
  - if [ "$CI_BUILD" = "autotools" ]; then make distcheck DISTCHECK_CONFIGURE_FLAGS="--with-mruby --with-neverbleed --enable-werror CPPFLAGS=-fsanitize=address LDFLAGS=\"-fsanitize=address -fuse-ld=gold\""; fi
  - if [ "$CI_BUILD" = "cmake" ]; then make check; fi
  # As of April, 23, 2016, golang http2 build fails, probably because
  # the default go version is too old.
  # - cd integration-tests
  # - export GOPATH="$PWD/integration-tests/golang"
  # - make itprep
  # - make it
